name: Your New Jekyll Site
#markdown: kramdown
markdown: redcarpet
baseurl: "/MessiJS"
permalink: pretty
pygments: true
exclude:
    - node_modules
    - Gemfile
    - Gemfile.lock
    - params.json
redcarpet:
    extensions:
        - no_intra_emphasis
        - fenced_code_blocks
        - autolink
        - tables
        - with_toc_data
